# Create a ClusterSecretStore to authenticate with GSM:
apiVersion: external-secrets.io/v1beta1
kind: SecretStore #ClusterSecretStore 
metadata:
  name: google-secret-store
  namespace: odi-dev #external-secrets
spec:
  provider:
    gcpsm:
      projectID: techplain-hub
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gsm-key #google-sa-key
            key: sa_SecretManager.key #key.json
            namespace: odi-dev
            
# kubectl create secret generic -n odi-dev gsm-key --from-file=secretManagsa_SecretManager.key=key.json
