apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-pull-db-creds
  namespace: odi-dev #external-secrets  # adjust namespace if needed
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-secret-store  # Ensure this refers to your configured store
    kind: SecretStore         # or ClusterSecretStore if that's what you're using
  target:
    name: database-creds      # The Kubernetes secret that will be created
  data:
    - secretKey: CONFIG_DB_ODIBETS_PASSWORD
      remoteRef:
        key: db_creds
        property: CONFIG_DB_ODIBETS_PASSWORD
    - secretKey: CONFIG_DB_ODIBETS_USERNAME
      remoteRef:
        key: db_creds
        property: CONFIG_DB_ODIBETS_USERNAME
    - secretKey: CONFIG_DB_WEB_HOST
      remoteRef:
        key: db_creds
        property: CONFIG_DB_WEB_HOST