apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: alpine:latest
        command: ["/bin/sh", "-c", "echo The secret is $PASSWORD && sleep 3600"]
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: cs-cred
              key: password
